ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "color" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "contactIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "shareToken" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "Event_shareToken_key" ON "Event"("shareToken") WHERE "shareToken" IS NOT NULL;
